name: Publish-Docker

on:
  push:
    # Publish `$default-branch` as Docker `latest` image.
    branches:
      - $default-branch

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: osrm-frontend

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file ./docker/Dockerfile --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          fi
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file ./docker/Dockerfile --tag $IMAGE_NAME --tag latest --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Google Cloud Container Registry
        uses: mattes/gce-docker-push-action@v1.0.0
        with:
          creds: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          src: $IMAGE_NAME:latest
          dst: asia.gcr.io/project-arc-236712/$IMAGE_NAME:${{github.run_number}}-${{github.sha}}
